spring:
  application:
    name: USER-MANAGEMENT-SERVICE
  datasource:
    url: jdbc:mysql://janith.ch0mg0sywvjb.ap-south-1.rds.amazonaws.com:3306/ead
    username: root
    password: wIvsa9-dykjon-suxcuq
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: jobgeniouslk@gmail.com
    password: gngr wzhx plnn anwo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost

server:
  port: 8081